name: Docker Action

on: [push]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run:  |
          docker build . -t ghcr.io/cosminionut1996/test_docker:latest

      - name: docker login
        env:
          REGISTRY: ghcr.io
          PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
          IMAGE_NAME: ${{ github.repository }}
          DOCKER_USER: cosminionut1996
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

        run: |
          echo "$PAT" | docker login ghcr.io -u $DOCKER_USER --password-stdin

      - name: docker push
        run: |
          docker push ghcr.io/cosminionut1996/test_docker:latest
